# version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # Mapeia a porta 80 do Nginx para a porta 3000 da máquina host
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
