version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"  # Porta do host: Porta do contêiner
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs  # Montar o diretório de logs para acesso externo, se necessário
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # Porta do host: Porta do Nginx no contêiner
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
