services:
  postgres:
    image: postgres:latest
    container_name: solana-db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: solana_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - solana-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: solana-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://usuario:senha123@postgres:5432/solana_db
    depends_on:
      - postgres
    networks:
      - solana-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: solana-frontend
    ports:
      - "80:80"  
    depends_on:
      - backend
    networks:
      - solana-network

volumes:
  postgres-data:

networks:
  solana-network:
    driver: bridge
